language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
before_install:
  - composer selfupdate
install:
  - composer install
script: 
  - ./vendor/bin/phpunit --colors --bootstrap tests/bootstrap.php --coverage-text tests
